apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.106
  selector:
    app: ftps
  ports:
  - name: ftps
    port: 21
    targetPort: 21
    protocol: TCP
  - name: pasv
    port: 30020
    targetPort: 30020
    protocol: TCP
  - name: pasv-1
    port: 30021
    targetPort: 30021
    protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 30021